services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:16-alpine #Versión Postgres 16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}   #Credenciales
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/docker/postgresql/data
    ports:
      - "2222:5432"

  # Servicio del backend (Express)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_backend
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    ports:
      - "3000:3000" #Puerto computadora local : puerto contenedor Docker

volumes:
  db_data:
